#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Tuple


ROOT = Path(__file__).resolve().parents[2]
SCHEMA_PATH = ROOT / "tools" / "coop" / "protocol_schema.json"
C_HEADER = ROOT / "src" / "mod" / "coop_protocol_generated.h"
PY_HEADER = ROOT / "tools" / "coop_bridge" / "protocol_generated.py"

PRIMS = {
    "u8": ("coop_u8", "B", 1, 1),
    "u16": ("coop_u16", "H", 2, 2),
    "u32": ("coop_u32", "I", 4, 4),
    "s32": ("coop_s32", "i", 4, 4),
    "f32": ("coop_f32", "f", 4, 4),
}


@dataclass(frozen=True)
class Layout:
    size: int
    align: int
    offsets: Dict[str, int]
    fmt: str


def align(value: int, boundary: int) -> int:
    return (value + boundary - 1) & ~(boundary - 1)


def load_schema() -> dict:
    return json.loads(SCHEMA_PATH.read_text(encoding="utf-8"))


def build_layouts(schema: dict) -> Dict[str, Layout]:
    layouts: Dict[str, Layout] = {}
    pending = dict(schema["structs"])
    while pending:
        progressed = False
        for name, fields in list(pending.items()):
            if any(field[0] not in PRIMS and field[0] not in layouts for field in fields):
                continue
            offset = 0
            max_align = 1
            offsets: Dict[str, int] = {}
            fmt = ">"
            for field in fields:
                typ, field_name = field[0], field[1]
                count = int(field[2]) if len(field) > 2 else 1
                if typ in PRIMS:
                    _, code, size, field_align = PRIMS[typ]
                    field_fmt = code * count
                else:
                    child = layouts[typ]
                    size, field_align = child.size, child.align
                    field_fmt = child.fmt[1:] * count
                offset = align(offset, field_align)
                offsets[field_name] = offset
                offset += size * count
                max_align = max(max_align, field_align)
                fmt += field_fmt
            layouts[name] = Layout(align(offset, max_align), max_align, offsets, fmt)
            del pending[name]
            progressed = True
        if not progressed:
            raise SystemExit("schema contains unresolved or cyclic struct references")
    return layouts


def iter_fields(schema: dict, struct_name: str) -> Iterable[Tuple[str, str, int]]:
    for field in schema["structs"][struct_name]:
        yield field[0], field[1], int(field[2]) if len(field) > 2 else 1


def c_decl(typ: str, name: str, count: int) -> str:
    ctyp = PRIMS[typ][0] if typ in PRIMS else f"struct {typ}"
    suffix = f"[{count}]" if count != 1 else ""
    return f"    {ctyp} {name}{suffix};"


def render_c(schema: dict, layouts: Dict[str, Layout]) -> str:
    lines: List[str] = [
        "/* Generated by tools/coop/generate_protocol.py. Do not edit by hand. */",
        "#ifndef COOP_PROTOCOL_GENERATED_H",
        "#define COOP_PROTOCOL_GENERATED_H",
        "",
        "typedef unsigned char coop_u8;",
        "typedef unsigned short coop_u16;",
        "typedef unsigned int coop_u32;",
        "typedef signed int coop_s32;",
        "typedef float coop_f32;",
        "",
        f"#define COOP_PROTOCOL_MAGIC 0x{schema['magic']:08X}u",
        f"#define COOP_PROTOCOL_ABI_VERSION {schema['abi_version']}u",
        f"#define COOP_GCBE7D_BUILD_ID 0x{schema['build_id']:08X}u",
        f"#define COOP_CAP_CUTBITS 0x{schema['capabilities']['cutbits']:08X}u",
        "#define COOP_STATUS_CONNECTED 0x00000001u",
        "#define COOP_STATUS_ACTIVE 0x00000002u",
        "#define COOP_STATUS_REMOTE_VALID 0x00000004u",
        "#define COOP_STATUS_ERROR 0x80000000u",
        "",
    ]
    for name in schema["structs"]:
        lines.append(f"struct {name} {{")
        for typ, field, count in iter_fields(schema, name):
            lines.append(c_decl(typ, field, count))
        lines.append("};")
        lines.append("")

    lines.extend(
        [
            "#define COOP_ASSERT_CAT2(a, b) a##b",
            "#define COOP_ASSERT_CAT(a, b) COOP_ASSERT_CAT2(a, b)",
            "#define COOP_STATIC_ASSERT(expr) typedef char COOP_ASSERT_CAT(coop_static_assert_, __LINE__)[(expr) ? 1 : -1]",
            "#define COOP_OFFSETOF(type, field) ((coop_u32)&(((type *)0)->field))",
            "",
        ]
    )
    for name, layout in layouts.items():
        lines.append(f"#define {name.upper()}_SIZE 0x{layout.size:X}u")
        lines.append(f"COOP_STATIC_ASSERT(sizeof(struct {name}) == {name.upper()}_SIZE);")
        for field, offset in layout.offsets.items():
            lines.append(
                f"COOP_STATIC_ASSERT(COOP_OFFSETOF(struct {name}, {field}) == 0x{offset:X}u);"
            )
        lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def render_py(schema: dict, layouts: Dict[str, Layout]) -> str:
    lines = [
        '"""Generated by tools/coop/generate_protocol.py. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        "import struct",
        "",
        f"MAGIC = 0x{schema['magic']:08X}",
        f"ABI_VERSION = {schema['abi_version']}",
        f"BUILD_ID = 0x{schema['build_id']:08X}",
        f"CAP_CUTBITS = 0x{schema['capabilities']['cutbits']:08X}",
        "STATUS_CONNECTED = 0x00000001",
        "STATUS_ACTIVE = 0x00000002",
        "STATUS_REMOTE_VALID = 0x00000004",
        "STATUS_ERROR = 0x80000000",
        "",
        "SIZES = {",
    ]
    for name, layout in layouts.items():
        lines.append(f"    {name!r}: {layout.size},")
    lines.extend(["}", "", "OFFSETS = {"])
    for name, layout in layouts.items():
        lines.append(f"    {name!r}: {{")
        for field, offset in layout.offsets.items():
            lines.append(f"        {field!r}: {offset},")
        lines.append("    },")
    lines.extend(["}", "", "FORMATS = {"])
    for name, layout in layouts.items():
        lines.append(f"    {name!r}: {layout.fmt!r},")
    lines.extend(
        [
            "}",
            "",
            "MAILBOX_SIZE = SIZES['CoopMailbox']",
            "SNAPSHOT_SIZE = SIZES['CoopSnapshot']",
            "",
            "def pack_values(struct_name: str, *values: object) -> bytes:",
            "    return struct.pack(FORMATS[struct_name], *values)",
            "",
            "def unpack_values(struct_name: str, data: bytes) -> tuple[object, ...]:",
            "    return struct.unpack(FORMATS[struct_name], data[:SIZES[struct_name]])",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    schema = load_schema()
    layouts = build_layouts(schema)
    outputs = {
        C_HEADER: render_c(schema, layouts),
        PY_HEADER: render_py(schema, layouts),
    }

    if args.check:
        bad = [path for path, content in outputs.items() if not path.exists() or path.read_text(encoding="utf-8") != content]
        if bad:
            for path in bad:
                print(f"out of date: {path}")
            return 1
        return 0

    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
