/* Generated by tools/coop/generate_protocol.py. Do not edit by hand. */
#ifndef COOP_PROTOCOL_GENERATED_H
#define COOP_PROTOCOL_GENERATED_H

typedef unsigned char coop_u8;
typedef unsigned short coop_u16;
typedef unsigned int coop_u32;
typedef signed int coop_s32;
typedef float coop_f32;

#define COOP_PROTOCOL_MAGIC 0x434F4C4Du
#define COOP_PROTOCOL_ABI_VERSION 1u
#define COOP_GCBE7D_BUILD_ID 0x47432447u
#define COOP_CAP_CUTBITS 0x00000001u
#define COOP_STATUS_CONNECTED 0x00000001u
#define COOP_STATUS_ACTIVE 0x00000002u
#define COOP_STATUS_REMOTE_VALID 0x00000004u
#define COOP_STATUS_ERROR 0x80000000u

struct CoopLocation {
    coop_s32 level;
    coop_s32 game_mode;
    coop_s32 hub;
    coop_s32 level_part_2;
    coop_s32 bonus;
    coop_s32 death;
    coop_s32 gem_path;
    coop_s32 vehicle_class;
};

struct CoopAvatar {
    coop_u32 flags;
    coop_u32 frame;
    coop_f32 pos_x;
    coop_f32 pos_y;
    coop_f32 pos_z;
    coop_u16 xrot;
    coop_u16 yrot;
    coop_u16 zrot;
    coop_u16 heading;
    coop_s32 character;
    coop_s32 action;
    coop_f32 anim_time;
    coop_s32 vehicle;
};

struct CoopProgress {
    coop_u32 revision;
    coop_u16 level_flags[35];
    coop_u8 hub_flags[6];
    coop_u8 hub_crystals[6];
    coop_u8 powerbits;
    coop_u8 gembits;
    coop_u8 reserved8[2];
    coop_u32 cutbits;
};

struct CoopSnapshot {
    coop_u32 status_flags;
    struct CoopLocation location;
    struct CoopAvatar avatar;
    struct CoopProgress progress;
};

struct CoopMailbox {
    coop_u32 magic;
    coop_u16 abi_version;
    coop_u16 struct_size;
    coop_u32 build_id;
    coop_u32 capabilities;
    coop_u32 game_heartbeat;
    coop_u32 bridge_heartbeat;
    coop_u32 local_seq;
    struct CoopSnapshot local_snapshot;
    coop_u32 inbound_seq;
    struct CoopSnapshot inbound_snapshot;
    coop_u32 last_applied_progress_revision;
    coop_u32 status_flags;
    coop_u32 reserved[8];
};

#define COOP_ASSERT_CAT2(a, b) a##b
#define COOP_ASSERT_CAT(a, b) COOP_ASSERT_CAT2(a, b)
#define COOP_STATIC_ASSERT(expr) typedef char COOP_ASSERT_CAT(coop_static_assert_, __LINE__)[(expr) ? 1 : -1]
#define COOP_OFFSETOF(type, field) ((coop_u32)&(((type *)0)->field))

#define COOPLOCATION_SIZE 0x20u
COOP_STATIC_ASSERT(sizeof(struct CoopLocation) == COOPLOCATION_SIZE);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, level) == 0x0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, game_mode) == 0x4u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, hub) == 0x8u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, level_part_2) == 0xCu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, bonus) == 0x10u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, death) == 0x14u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, gem_path) == 0x18u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopLocation, vehicle_class) == 0x1Cu);

#define COOPAVATAR_SIZE 0x2Cu
COOP_STATIC_ASSERT(sizeof(struct CoopAvatar) == COOPAVATAR_SIZE);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, flags) == 0x0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, frame) == 0x4u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, pos_x) == 0x8u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, pos_y) == 0xCu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, pos_z) == 0x10u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, xrot) == 0x14u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, yrot) == 0x16u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, zrot) == 0x18u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, heading) == 0x1Au);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, character) == 0x1Cu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, action) == 0x20u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, anim_time) == 0x24u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopAvatar, vehicle) == 0x28u);

#define COOPPROGRESS_SIZE 0x60u
COOP_STATIC_ASSERT(sizeof(struct CoopProgress) == COOPPROGRESS_SIZE);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, revision) == 0x0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, level_flags) == 0x4u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, hub_flags) == 0x4Au);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, hub_crystals) == 0x50u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, powerbits) == 0x56u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, gembits) == 0x57u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, reserved8) == 0x58u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopProgress, cutbits) == 0x5Cu);

#define COOPSNAPSHOT_SIZE 0xB0u
COOP_STATIC_ASSERT(sizeof(struct CoopSnapshot) == COOPSNAPSHOT_SIZE);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopSnapshot, status_flags) == 0x0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopSnapshot, location) == 0x4u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopSnapshot, avatar) == 0x24u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopSnapshot, progress) == 0x50u);

#define COOPMAILBOX_SIZE 0x1A8u
COOP_STATIC_ASSERT(sizeof(struct CoopMailbox) == COOPMAILBOX_SIZE);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, magic) == 0x0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, abi_version) == 0x4u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, struct_size) == 0x6u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, build_id) == 0x8u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, capabilities) == 0xCu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, game_heartbeat) == 0x10u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, bridge_heartbeat) == 0x14u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, local_seq) == 0x18u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, local_snapshot) == 0x1Cu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, inbound_seq) == 0xCCu);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, inbound_snapshot) == 0xD0u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, last_applied_progress_revision) == 0x180u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, status_flags) == 0x184u);
COOP_STATIC_ASSERT(COOP_OFFSETOF(struct CoopMailbox, reserved) == 0x188u);

#endif
