"""Generated by tools/coop/generate_protocol.py. Do not edit by hand."""

from __future__ import annotations

import struct

MAGIC = 0x434F4C4D
ABI_VERSION = 1
BUILD_ID = 0x47432447
CAP_CUTBITS = 0x00000001
STATUS_CONNECTED = 0x00000001
STATUS_ACTIVE = 0x00000002
STATUS_REMOTE_VALID = 0x00000004
STATUS_ERROR = 0x80000000

SIZES = {
    'CoopLocation': 32,
    'CoopAvatar': 44,
    'CoopProgress': 96,
    'CoopSnapshot': 176,
    'CoopMailbox': 424,
}

OFFSETS = {
    'CoopLocation': {
        'level': 0,
        'game_mode': 4,
        'hub': 8,
        'level_part_2': 12,
        'bonus': 16,
        'death': 20,
        'gem_path': 24,
        'vehicle_class': 28,
    },
    'CoopAvatar': {
        'flags': 0,
        'frame': 4,
        'pos_x': 8,
        'pos_y': 12,
        'pos_z': 16,
        'xrot': 20,
        'yrot': 22,
        'zrot': 24,
        'heading': 26,
        'character': 28,
        'action': 32,
        'anim_time': 36,
        'vehicle': 40,
    },
    'CoopProgress': {
        'revision': 0,
        'level_flags': 4,
        'hub_flags': 74,
        'hub_crystals': 80,
        'powerbits': 86,
        'gembits': 87,
        'reserved8': 88,
        'cutbits': 92,
    },
    'CoopSnapshot': {
        'status_flags': 0,
        'location': 4,
        'avatar': 36,
        'progress': 80,
    },
    'CoopMailbox': {
        'magic': 0,
        'abi_version': 4,
        'struct_size': 6,
        'build_id': 8,
        'capabilities': 12,
        'game_heartbeat': 16,
        'bridge_heartbeat': 20,
        'local_seq': 24,
        'local_snapshot': 28,
        'inbound_seq': 204,
        'inbound_snapshot': 208,
        'last_applied_progress_revision': 384,
        'status_flags': 388,
        'reserved': 392,
    },
}

FORMATS = {
    'CoopLocation': '>iiiiiiii',
    'CoopAvatar': '>IIfffHHHHiifi',
    'CoopProgress': '>IHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHBBBBBBBBBBBBBBBBI',
    'CoopSnapshot': '>IiiiiiiiiIIfffHHHHiifiIHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHBBBBBBBBBBBBBBBBI',
    'CoopMailbox': '>IHHIIIIIIiiiiiiiiIIfffHHHHiifiIHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHBBBBBBBBBBBBBBBBIIIiiiiiiiiIIfffHHHHiifiIHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHBBBBBBBBBBBBBBBBIIIIIIIIIII',
}

MAILBOX_SIZE = SIZES['CoopMailbox']
SNAPSHOT_SIZE = SIZES['CoopSnapshot']

def pack_values(struct_name: str, *values: object) -> bytes:
    return struct.pack(FORMATS[struct_name], *values)

def unpack_values(struct_name: str, data: bytes) -> tuple[object, ...]:
    return struct.unpack(FORMATS[struct_name], data[:SIZES[struct_name]])
