#!/usr/bin/env python3
"""Pick the next unit to work on for a decomp agent.

Default mode: weighted-random selection from units that still have unmatched
functions, biased toward units with more remaining work.  Pass --list to browse
interactively, --category to filter, or an explicit unit name to skip selection.

Units currently claimed by other dashboard agents (tracked via a simple lock
directory) are excluded automatically.
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

from ai_common import (
    DEFAULT_VERSION,
    find_units,
    format_percent,
    load_repo_index,
    next_unmatched_function,
    ranked_unit_functions,
)


ROOT = Path(__file__).resolve().parent.parent
LOCK_DIR = ROOT / ".pi" / "agent-locks"


# ---------------------------------------------------------------------------
# Lock helpers – lightweight file-based claim system
# ---------------------------------------------------------------------------

def read_locks() -> dict[str, dict[str, Any]]:
    """Return {normalized_unit_name: lock_payload} for every active lock."""
    if not LOCK_DIR.is_dir():
        return {}
    locks: dict[str, dict[str, Any]] = {}
    for lock_file in LOCK_DIR.glob("*.json"):
        try:
            payload = json.loads(lock_file.read_text(encoding="utf-8"))
            unit_name = payload.get("unit", lock_file.stem)
            locks[unit_name] = payload
        except (json.JSONDecodeError, OSError):
            continue
    return locks


def claim_unit(unit_name: str, agent_id: str) -> Path:
    """Write a lock file for *unit_name* owned by *agent_id*."""
    LOCK_DIR.mkdir(parents=True, exist_ok=True)
    safe_name = unit_name.replace("/", "__").replace("\\", "__")
    lock_path = LOCK_DIR / f"{safe_name}.json"
    lock_path.write_text(
        json.dumps({"unit": unit_name, "agent": agent_id}),
        encoding="utf-8",
    )
    return lock_path


def release_unit(unit_name: str) -> None:
    """Remove the lock file for *unit_name* if it exists."""
    safe_name = unit_name.replace("/", "__").replace("\\", "__")
    lock_path = LOCK_DIR / f"{safe_name}.json"
    lock_path.unlink(missing_ok=True)


def release_agent(agent_id: str) -> None:
    """Remove all lock files owned by *agent_id*."""
    for lock_file in LOCK_DIR.glob("*.json") if LOCK_DIR.is_dir() else []:
        try:
            payload = json.loads(lock_file.read_text(encoding="utf-8"))
            if payload.get("agent") == agent_id:
                lock_file.unlink(missing_ok=True)
        except (json.JSONDecodeError, OSError):
            continue


# ---------------------------------------------------------------------------
# Candidate scoring
# ---------------------------------------------------------------------------

def unit_remaining_work(unit) -> tuple[int, int]:
    """Return (remaining_functions, remaining_code_bytes)."""
    total_fn = int(unit.measures.get("total_functions") or 0)
    matched_fn = int(unit.measures.get("matched_functions") or 0)
    total_code = int(unit.measures.get("total_code") or 0)
    matched_code = int(unit.measures.get("matched_code") or 0)
    return max(total_fn - matched_fn, 0), max(total_code - matched_code, 0)


def eligible_units(index, version: str, category: str | None, locked_names: set[str]):
    """Yield (unit, remaining_fn, remaining_code) for workable units."""
    for unit in index.units.values():
        if not unit.measures:
            continue
        remaining_fn, remaining_code = unit_remaining_work(unit)
        if remaining_fn == 0:
            continue
        if unit.normalized_name in locked_names:
            continue
        if category and category not in unit.progress_categories:
            continue
        # Skip SDK units – they're autogenerated stubs
        if "sdk" in unit.progress_categories:
            continue
        yield unit, remaining_fn, remaining_code


def pick_random_weighted(candidates: list[tuple[Any, int, int]]) -> Any:
    """Weighted-random: more remaining code → higher chance, but not deterministic."""
    if not candidates:
        return None
    weights = [max(remaining_code, 64) for _, _, remaining_code in candidates]
    chosen = random.choices(candidates, weights=weights, k=1)[0]
    return chosen[0]


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def print_candidates(candidates, version: str, limit: int = 30) -> None:
    candidates.sort(key=lambda c: c[2], reverse=True)
    print(f"Eligible units ({len(candidates)} total, showing up to {limit}):\n")
    print(f"  {'#':<4} {'Unit':<36} {'Remaining Fn':>14} {'Remaining Code':>14} {'Match%':>8}")
    print(f"  {'─'*4} {'─'*36} {'─'*14} {'─'*14} {'─'*8}")
    for i, (unit, rem_fn, rem_code) in enumerate(candidates[:limit], 1):
        matched_pct = unit.measures.get("matched_code_percent")
        print(
            f"  {i:<4} {unit.normalized_name:<36} {rem_fn:>14} {rem_code:>14} "
            f"{format_percent(float(matched_pct) if matched_pct is not None else None):>8}"
        )


def main() -> int:
    parser = argparse.ArgumentParser(description="Pick the next unit for a decomp agent.")
    parser.add_argument("unit", nargs="?", default=None, help="Explicit unit name (skip random selection)")
    parser.add_argument("--version", default=DEFAULT_VERSION)
    parser.add_argument("--category", default=None, help="Filter to progress category (e.g. gameplay, engine_3d)")
    parser.add_argument("--agent-id", default=None, help="Agent identifier for lock tracking")
    parser.add_argument("--claim", action="store_true", help="Write a lock file after picking")
    parser.add_argument("--release", action="store_true", help="Release the lock for the given unit or agent-id")
    parser.add_argument("--list", action="store_true", help="List eligible units instead of picking one")
    parser.add_argument("--json", action="store_true", help="Emit JSON output")
    parser.add_argument("--limit", type=int, default=30, help="Max units to show in --list mode")
    args = parser.parse_args()

    if args.release:
        if args.unit:
            release_unit(args.unit)
            print(f"Released lock for unit: {args.unit}")
        elif args.agent_id:
            release_agent(args.agent_id)
            print(f"Released all locks for agent: {args.agent_id}")
        else:
            print("--release requires a unit argument or --agent-id", file=sys.stderr)
            return 1
        return 0

    index = load_repo_index(args.version)
    locked = set(read_locks().keys())
    candidates = list(eligible_units(index, args.version, args.category, locked))

    if args.list:
        if args.json:
            payload = [
                {"unit": u.normalized_name, "remaining_fn": rfn, "remaining_code": rc,
                 "matched_code_percent": u.measures.get("matched_code_percent")}
                for u, rfn, rc in sorted(candidates, key=lambda c: c[2], reverse=True)[:args.limit]
            ]
            print(json.dumps(payload, indent=2))
        else:
            print_candidates(candidates, args.version, args.limit)
        return 0

    if args.unit:
        matches = find_units(args.unit, version=args.version)
        if not matches:
            print(f"No unit found for '{args.unit}'", file=sys.stderr)
            return 1
        chosen = matches[0]
    else:
        chosen = pick_random_weighted(candidates)
        if chosen is None:
            print("No eligible units found.", file=sys.stderr)
            return 1

    if args.claim and args.agent_id:
        claim_unit(chosen.normalized_name, args.agent_id)

    if args.json:
        remaining_fn, remaining_code = unit_remaining_work(chosen)
        nf = next_unmatched_function(chosen)
        payload = {
            "unit": chosen.normalized_name,
            "source_path": chosen.source_path,
            "remaining_functions": remaining_fn,
            "remaining_code": remaining_code,
            "matched_code_percent": chosen.measures.get("matched_code_percent"),
            "next_function": {
                "name": nf.name,
                "address": nf.address,
                "size": nf.size,
                "fuzzy_match_percent": nf.fuzzy_match_percent,
            } if nf else None,
        }
        print(json.dumps(payload, indent=2))
    else:
        remaining_fn, remaining_code = unit_remaining_work(chosen)
        print(f"Picked: {chosen.normalized_name}")
        if chosen.source_path:
            print(f"Source: {chosen.source_path}")
        pct = chosen.measures.get("matched_code_percent")
        print(f"Remaining: {remaining_fn} functions, {remaining_code} bytes code")
        print(f"Matched code: {format_percent(float(pct) if pct is not None else None)}")
        nf = next_unmatched_function(chosen)
        if nf:
            print(f"Next function: {nf.name} (0x{nf.address:08X}, match {format_percent(nf.fuzzy_match_percent)})")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
