name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    container:
      image: ghcr.io/denzi-gh/crashwoc-decomp-build:main
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - GCBE7D

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Git config
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Restore timestamps
        run: |
          git config --global alias.whatchanged "log --raw --no-merges"
          uv run https://raw.githubusercontent.com/MestreLion/git-tools/refs/tags/v2022.12/git-restore-mtime \
              --merge --commit-time

      - name: Prepare
        run: cp -a /orig .

      - name: Install Wine
        run: |
          ALPINE_VER="$(cut -d. -f1,2 /etc/alpine-release)"
          echo "https://dl-cdn.alpinelinux.org/alpine/v${ALPINE_VER}/community" >> /etc/apk/repositories
          apk add --no-cache wine

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: |
            build
            .ninja_deps
            .ninja_log
          key: ${{ runner.os }}-${{ matrix.version }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-${{ matrix.version }}-

      - name: Build
        env:
          HOME: /tmp/crashwoc-home
          WINEPREFIX: /tmp/crashwoc-wine
          WINEDEBUG: -all
          XDG_RUNTIME_DIR: /tmp/crashwoc-xdg
        run: |
          mkdir -p "$HOME" "$WINEPREFIX" "$XDG_RUNTIME_DIR"
          python configure.py --map --version ${{ matrix.version }} \
              --binutils /binutils --compilers /compilers --wrapper wine
          ninja all_source progress build/${{ matrix.version }}/report.json

      - name: Upload map
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_maps
          path: build/${{ matrix.version }}/**/*.MAP
          if-no-files-found: ignore

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.version }}_report
          path: build/${{ matrix.version }}/report.json
